server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**

        - id: ms-citas
          uri: lb://ms-citas
          predicates:
            - Path=/api/citas/**
          filters:
            - AuthenticationFilter

        - id: ms-especialidades
          uri: lb://ms-especialidades
          predicates:
            - Path=/api/especialidades/**
          filters:
            - AuthenticationFilter

        - id: ms-fichas-clinicas
          uri: lb://ms-fichas-clinicas
          predicates:
            - Path=/api/fichas-clinicas/**
          filters:
            - AuthenticationFilter

        - id: ms-horarios
          uri: lb://ms-horarios
          predicates:
            - Path=/api/horarios/**
          filters:
            - AuthenticationFilter

        - id: ms-medicos
          uri: lb://ms-medicos
          predicates:
            - Path=/api/medicos/**
          filters:
            - AuthenticationFilter

        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - AuthenticationFilter

        - id: ms-pacientes
          uri: lb://ms-pacientes
          predicates:
            - Path=/api/pacientes/**
          filters:
            - AuthenticationFilter

        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**
          filters:
            - AuthenticationFilter

        - id: ms-recetas
          uri: lb://ms-recetas
          predicates:
            - Path=/api/recetas/**
          filters:
            - AuthenticationFilter

springdoc:
  swagger-ui:
    urls:
      - name: ms-auth
        url: /ms-auth/v3/api-docs

      - name: ms-citas
        url: /ms-citas/v3/api-docs

      - name: ms-especialidades
        url: /ms-especialidades/v3/api-docs

      - name: ms-medicos
        url: /ms-medicos/v3/api-docs

      - name: ms-pacientes
        url: /ms-pacientes/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: EstaEsUnaLlaveMuySecretaYQueDebeSerLargaParaQueFuncione12345
